version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80" 
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    environment:
      - NODE_ENV=production
